BEGIN;
ALTER TABLE usuarios ADD COLUMN IF NOT EXISTS auth_version INTEGER NOT NULL DEFAULT 0;
CREATE TABLE IF NOT EXISTS codigos_acceso (
  usuario_id INTEGER PRIMARY KEY REFERENCES usuarios(id),
  nonce TEXT NOT NULL,
  codigo_hash TEXT NOT NULL,
  intentos INTEGER NOT NULL DEFAULT 0,
  vence TIMESTAMPTZ NOT NULL,
  usado BOOLEAN NOT NULL DEFAULT false
);
COMMIT;
