import { useState } from 'react';
import { useRemote,jsonRequest } from '../hooks/useRemote.js';
const vacio={nombre:'',zona:'',lote:'',tipo:'socio',cuota_base:'',usuario_id:''};
export default function Padron(){
 const [buscar,setBuscar]=useState('');const r=useRemote(`/api/socios?buscar=${encodeURIComponent(buscar)}`),cuentas=useRemote('/api/socios/cuentas/disponibles');
 const [form,setForm]=useState(null),[mensaje,setMensaje]=useState(''),[busy,setBusy]=useState(false);
 async function guardar(e){e.preventDefault();setBusy(true);try{await jsonRequest(form.id?`/api/socios/${form.id}`:'/api/socios',form.id?'PUT':'POST',form);setForm(null);setMensaje('Socio guardado.');r.refresh();}catch(e){setMensaje(e.message);}finally{setBusy(false);}}
 async function estado(s){if(!window.confirm(`${s.estado?'Desactivar':'Activar'} a ${s.nombre}?`))return;try{await jsonRequest(`/api/socios/${s.id}/estado`,'PATCH',{estado:!s.estado});r.refresh();}catch(e){setMensaje(e.message);}}
 return <section className="panel-box club-panel"><h1>Padrón de socios</h1><p>Vincula cada propiedad con su cuenta para que el socio vea sus cuotas y envíe pagos.</p><div className="club-actions"><input aria-label="Buscar socio" placeholder="Buscar nombre, zona o lote" value={buscar} onChange={e=>setBuscar(e.target.value)}/><button onClick={()=>setForm({...vacio})}>Nuevo socio</button><button onClick={r.refresh}>Actualizar</button></div>{mensaje&&<p role="status">{mensaje}</p>}{r.error&&<p role="alert">{r.error}</p>}
 {form&&<form className="club-form" onSubmit={guardar}><h2>{form.id?'Editar':'Registrar'} socio</h2>{[['nombre','Nombre'],['zona','Zona'],['lote','Lote'],['tipo','Tipo'],['cuota_base','Cuota mensual']].map(([key,label])=><label key={key}>{label}<input value={form[key]??''} onChange={e=>setForm({...form,[key]:e.target.value})} type={key==='cuota_base'?'number':'text'} min="0" step="0.01" required maxLength={160}/></label>)}<label>Cuenta vinculada<select value={form.usuario_id||''} onChange={e=>setForm({...form,usuario_id:e.target.value})}><option value="">Sin vincular</option>{cuentas.data?.map(c=><option value={c.id} key={c.id}>{c.nombre} — {c.correo}</option>)}</select></label>{cuentas.error&&<p role="alert">{cuentas.error}</p>}<button disabled={busy}>Guardar</button><button type="button" onClick={()=>setForm(null)}>Cancelar</button></form>}
 {r.loading?<p>Cargando…</p>:<div className="club-table"><table><thead><tr><th>Socio</th><th>Propiedad</th><th>Cuota</th><th>Cuenta</th><th>Estado</th><th>Acciones</th></tr></thead><tbody>{r.data?.map(s=><tr key={s.id}><td>{s.nombre}</td><td>{s.zona}-{s.lote}</td><td>S/ {Number(s.cuota_base).toFixed(2)}</td><td>{s.usuario_id?cuentas.data?.find(c=>c.id===s.usuario_id)?.correo||`#${s.usuario_id}`:'Sin vincular'}</td><td>{s.estado?'Activo':'Inactivo'}</td><td><button onClick={()=>setForm(s)}>Editar</button><button onClick={()=>estado(s)}>{s.estado?'Desactivar':'Activar'}</button></td></tr>)}</tbody></table></div>}</section>;
}
