import { useState } from 'react';
import { useRemote } from '../../hooks/useRemote.js';
import { apiFetch } from '../../api.js';
const dinero=n=>Number(n||0).toFixed(2);
export default function CuotasPortal(){
 const {data,error,loading,refresh}=useRemote('/api/portal/cuotas');const [seleccion,setSeleccion]=useState(null),[mensaje,setMensaje]=useState(''),[busy,setBusy]=useState(false);
 async function enviar(e){e.preventDefault();setBusy(true);setMensaje('');const form=e.currentTarget;try{const body=new FormData(form);body.set('cuotaId',seleccion.id);const r=await apiFetch('/api/portal/pagos',{method:'POST',body});const d=await r.json();if(!r.ok)throw new Error(d.mensaje);setMensaje(d.mensaje);setSeleccion(null);refresh();}catch(e){setMensaje(e.message);}finally{setBusy(false);}}
 return <section className="panel-box club-panel"><h1>Mis cuotas</h1><button onClick={refresh}>Actualizar</button>{mensaje&&<p role="status">{mensaje}</p>}{error&&<p role="alert">{error}</p>}{loading?<p>Cargando…</p>:data&&!data.socios.length?<p>Tu cuenta aún no está vinculada al padrón. Solicita a administración que la vincule con tu propiedad.</p>:<><p>Saldo pendiente: <strong>S/ {dinero(data?.cuotas.reduce((s,c)=>s+Number(c.saldo),0))}</strong></p><div className="club-table"><table><thead><tr><th>Propiedad</th><th>Periodo</th><th>Cuota</th><th>Pagado</th><th>Saldo</th><th>En revisión</th><th>Acción</th></tr></thead><tbody>{data?.cuotas.map(c=><tr key={c.id}><td>{c.zona}-{c.lote}</td><td>{c.mes}/{c.anio}</td><td>S/ {dinero(c.monto)}</td><td>S/ {dinero(c.pagado)}</td><td>S/ {dinero(c.saldo)}</td><td>S/ {dinero(c.en_revision)}</td><td>{Number(c.disponible)>0&&<button onClick={()=>{setSeleccion(c);setMensaje('');}}>Enviar pago</button>}</td></tr>)}</tbody></table></div>{data?.cuotas.length===0&&<p>No hay cuotas generadas todavía.</p>}</>}
 {seleccion&&<form className="club-form" onSubmit={enviar} key={seleccion.id}><h2>Pago de {seleccion.mes}/{seleccion.anio}</h2><label>Monto (máximo S/ {dinero(seleccion.disponible)})<input name="monto" type="number" min="0.01" max={seleccion.disponible} step="0.01" defaultValue={seleccion.disponible} required /></label><label>Fecha del pago<input name="fechaPago" type="date" required /></label><label>Método<select name="metodoPago" required><option value="">Selecciona</option>{['Transferencia','Yape','Plin','Depósito','Efectivo'].map(m=><option key={m}>{m}</option>)}</select></label><label>Referencia<input name="referencia" maxLength={120}/></label><label>Comprobante<input name="comprobante" type="file" accept="image/png,image/jpeg,image/webp" required/></label><p>El saldo se actualizará cuando administración apruebe el pago.</p><button disabled={busy}>{busy?'Enviando…':'Enviar comprobante'}</button><button type="button" onClick={()=>setSeleccion(null)}>Cancelar</button></form>}</section>;
}
